---
- name: Test copying a file into Git repo
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Copy test file from pwd into repo
      ansible.builtin.copy:
        src: test_file.txt
        dest: /path/to/your/git/repo/test_file.txt

